name: Laba6

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rabota:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            cpack_flag: WIX
            extension: msi
          - os: macos-latest
            cpack_flag: DragNDrop
            extension: dmg
          - os: ubuntu-latest
            cpack_flag: DEB
            extension: deb
          - os: ubuntu-latest
            cpack_flag: RPM
            extension: rpm
          - os: ubuntu-latest
            cpack_flag: TGZ
            extension: tar.gz
          - os: ubuntu-latest
            cpack_flag: ZIP
            extension: zip 

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y cmake
        sudo apt-get install rpm

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Create deb package
      working-directory: ${{github.workspace}}/build
      run: cpack -G ${{ matrix.cpack_flag }}
     
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: ${{ matrix.os }}-${{ matrix.extension }}-pack
          path: build/*.${{ matrix.extension }}

  create_release:
    needs: rabota
    runs-on: ubuntu-latest
    permissions:
       contents: write 

    steps:
    - uses: actions/checkout@v4

    - name: download_windows
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-msi-pack
        path: artifacts/windows

    - name: download_macos
      uses: actions/download-artifact@v4 
      with:
        name: macos-latest-dmg-pack
        path: artifacts/macos

    - name: download_ubuntu_deb
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-deb-pack
        path: artifacts/linux

    - name: download_ubuntu_rpm
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-rpm-pack
        path: artifacts/linux
    
    - name: download_ubuntu_zip
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-zip-pack
        path: artifacts/linux

    - name: download_ubuntu_tgz
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-tar.gz-pack
        path: artifacts/linux   

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        files: |
          artifacts/linux/*.deb
          artifacts/linux/*.rpm
          artifacts/windows/*.msi
          artifacts/macos/*.dmg
          artifacts/linux/*.zip
          artifacts/linux/*.tar.gz  
